### ISSUE TITLE
The detailed blog link is broken, and what is the FPS on which mobile phone ?

### ISSUE THREAD

**Issue by wwdok** [KernelErr/realtime-object-detector#2]

**Comment by KernelErr** [comment]
Thanks for your support. Currently, my blog is under migration due to unexpected reasons. Till now, it has been restored, so you can visit it.
The FPS rate is 30 on my phone with HUAWEI Kirin 810. However, some frames would not be handled by Paddle Lite if it's busy processing previous ones. So you still can feel obvious lags if you don't use some light models.

**Comment by KernelErr** [comment]
By the way, my advice is to lighten the model and drop some frames manually. I don't really know if the camera plugin I used for Flutter development is fixed the FPS rate or it's my performance bottleneck.

**Comment by wwdok** [comment]
I have seen the link issue was fixed ！And thanks for your information and advice！
